import Nav from "../../components/landing/Nav";
import Footer from "../../components/landing/Footer";
import FadeIn from "../../components/landing/FadeIn";
import "../Landing/LandingPage.css";
import "../Docs/DocsPage.css";

export default function PrivacyPage() {
  return (
    <div className="landing-root">
      <div className="land-noise" />
      <Nav />

      <section className="land-sec" style={{ paddingTop: 40 }}>
        <div className="land-con" style={{ maxWidth: 820 }}>
          <FadeIn>
            <div className="docs-content">
              <h1 className="docs-content-title">Privacy Policy</h1>
              <div className="docs-content-body">
                <p><strong>Effective Date:</strong> March 11, 2026</p>
                <p>
                  Releaslyy ("we", "our", "us") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, and safeguard your information when you use our AI-powered release notes platform.
                </p>

                <h3>1. Information We Collect</h3>
                <p><strong>Account Information</strong></p>
                <ul>
                  <li>Name, email address, and profile picture provided through Google OAuth sign-in.</li>
                  <li>We do not store your Google password.</li>
                </ul>
                <p><strong>Integration Data</strong></p>
                <ul>
                  <li>API tokens and OAuth credentials you provide to connect third-party services (GitHub, DevRev, Jira, etc.).</li>
                  <li>All tokens are encrypted at rest using AES-256-GCM encryption.</li>
                  <li>Repository names, branch names, commit messages, pull request titles, sprint data, and issue details fetched from connected integrations.</li>
                </ul>
                <p><strong>Generated Content</strong></p>
                <ul>
                  <li>Release notes generated by the AI, including titles, content, audience, and source metadata.</li>
                </ul>
                <p><strong>Usage Data</strong></p>
                <ul>
                  <li>Session information for authentication purposes (stored server-side using HTTP-only cookies).</li>
                </ul>

                <h3>2. How We Use Your Information</h3>
                <ul>
                  <li><strong>Authentication</strong> — To verify your identity and manage your account sessions.</li>
                  <li><strong>Integration Access</strong> — To fetch data from your connected tools (commits, issues, sprints) for release note generation.</li>
                  <li><strong>AI Generation</strong> — To send relevant data to our AI provider (Groq) for generating release notes. Only the specific data you select (commits, issues) is sent.</li>
                  <li><strong>Storage</strong> — To save your generated release notes so you can access, edit, and export them later.</li>
                </ul>

                <h3>3. Data Sharing</h3>
                <p>We do not sell, trade, or rent your personal information. Your data may be shared only in these limited circumstances:</p>
                <ul>
                  <li><strong>AI Processing</strong> — Selected commit messages, issue summaries, and sprint data are sent to Groq's API for release note generation. This data is used solely for processing your request and is not retained by the AI provider for training purposes.</li>
                  <li><strong>Third-Party Integrations</strong> — When you connect a service (GitHub, Jira, DevRev), we communicate with their APIs using your stored credentials to fetch the data you request.</li>
                  <li><strong>Legal Requirements</strong> — If required by law, regulation, or legal process.</li>
                </ul>

                <h3>4. Data Security</h3>
                <ul>
                  <li>All API tokens and OAuth credentials are encrypted using AES-256-GCM before storage.</li>
                  <li>Sessions are managed with HTTP-only, secure cookies.</li>
                  <li>All communication between the client and server uses HTTPS.</li>
                  <li>Database connections are encrypted with SSL/TLS in production.</li>
                </ul>

                <h3>5. Data Retention</h3>
                <ul>
                  <li>Your account data is retained as long as your account is active.</li>
                  <li>Generated release notes are stored until you delete them.</li>
                  <li>Integration tokens are stored until you disconnect the integration.</li>
                  <li>Sessions expire after 7 days of inactivity.</li>
                </ul>

                <h3>6. Your Rights</h3>
                <p>You have the right to:</p>
                <ul>
                  <li><strong>Access</strong> your stored data through the application dashboard.</li>
                  <li><strong>Delete</strong> your release notes at any time from the dashboard.</li>
                  <li><strong>Disconnect</strong> any integration, which removes the stored credentials.</li>
                  <li><strong>Request deletion</strong> of your account and all associated data by contacting us.</li>
                </ul>

                <h3>7. Cookies</h3>
                <p>
                  We use a single session cookie for authentication. This is an HTTP-only cookie that cannot be accessed by client-side scripts. We do not use tracking cookies, analytics cookies, or third-party advertising cookies.
                </p>

                <h3>8. Children's Privacy</h3>
                <p>
                  Releaslyy is not intended for use by individuals under the age of 13. We do not knowingly collect personal information from children.
                </p>

                <h3>9. Changes to This Policy</h3>
                <p>
                  We may update this Privacy Policy from time to time. Any changes will be reflected on this page with an updated effective date. Continued use of the platform after changes constitutes acceptance of the revised policy.
                </p>

                <h3>10. Contact Us</h3>
                <p>
                  If you have any questions about this Privacy Policy or your data, please reach out to us through the contact information provided on our website.
                </p>
              </div>
            </div>
          </FadeIn>
        </div>
      </section>

      <Footer />
    </div>
  );
}
